# Auto-generated by `tools/build_round3_uploadsafe_variants.py`.
# This file is intended for single-file IMC uploads.

# Variant source: `fundamental_drift_basis_hedged_v1.py`
# Embedded base: `fundamental_drift_guard_uploadsafe_v1.py`

"""
Round 3 fundamental_v1 — parameterized, tune-friendly reference build.

Design principles:
1. HYDROGEL_PACK is an independent stationary product. Trade it on its
   own anchor / inventory logic. Do not tie it to the other contracts.
2. VELVETFRUIT_EXTRACT is the true underlying for the voucher chain.
   Use it as the primary fair-value input, not as a direct pair-trade
   leg against the vouchers.
3. VEV_4000 and VEV_4500 are deep-ITM calls, i.e. synthetic spot with
   wide spreads. Their executable edge is in pricing THEM off the
   tighter underlying, not in crossing spot against them.
4. The sibling deep-ITM voucher is used as a confirmation signal:
   if the sibling-implied synthetic spot disagrees materially with the
   observed underlying, reduce aggression because one leg is probably
   noisy. This is the cross-contract relationship that actually makes
   sense fundamentally.

This file is meant to be readable and tunable. Most knobs are grouped
at the top by sleeve.
"""
from typing import Dict, List, Optional, Tuple
from statistics import NormalDist
import json
import math

from datamodel import Order, OrderDepth, TradingState


_N = NormalDist()
DAYS_PER_YEAR = 365
TTE_DAYS_LIVE = 5.0


class BaseTrader:
    LIMITS = {
        "HYDROGEL_PACK": 200,
        "VELVETFRUIT_EXTRACT": 200,
        "VEV_4000": 300,
        "VEV_4500": 300,
        "VEV_5000": 300,
        "VEV_5100": 300,
        "VEV_5200": 300,
        "VEV_5300": 300,
        "VEV_5400": 300,
        "VEV_5500": 300,
        "VEV_6000": 300,
        "VEV_6500": 300,
    }

    VOUCHER_STRIKES = {"VEV_4000": 4000, "VEV_4500": 4500}

    # ---------- HYDROGEL_PACK ----------
    # Independent stationary anchor product.
    H_ANCHOR = 9990.0
    H_CLIP = 30.0
    H_TAKE_EDGE = 0.0
    H_REDUCE_EDGE = 1.0
    H_PENNY_EDGE = 1.5
    H_INV_SKEW = 0.015
    H_MAX_POST_SIZE = 20
    H_PASSIVE_OFFSET = 8.0
    H_WIDE_SPREAD = 8
    H_SHOCK_MOVE = 15.0
    H_ENDGAME_START = 985000
    H_ENDGAME_POS = 150
    H_ENDGAME_CHUNK = 30

    # ---------- DEEP-ITM VOUCHERS ----------
    # Spot-anchored fair values with sibling confirmation.
    V_SIGMA = 0.23
    V_TAKE_EDGE = 0.0
    V_REDUCE_EDGE = 0.0
    V_PENNY_EDGE = 1.0
    V_INV_SKEW = 0.005
    V_MAX_POST_SIZE = 40
    V_WIDE_SPREAD = 3

    # Cross-contract relationship knobs:
    # sibling_implied_spot = sibling_mid + sibling_strike
    # If sibling_implied_spot disagrees too much with VFE spot, trust the
    # setup less and quote smaller / require more edge.
    V_CONFIRM_THRESHOLD = 2.5
    V_CONFIRM_WIDEN = 0.5
    V_CONFIRM_SIZE_MULT = 0.5

    # Optional tiny blend from sibling synthetic into spot estimate.
    # Keep this small; spot is still the primary truth source.
    V_SIBLING_BLEND = 0.10
    V_SIBLING_BLEND_CAP = 4.0

    V_ENDGAME_START = 980000
    V_ENDGAME_POS = 120
    V_ENDGAME_CHUNK = 25

    # ---------- OPTIONAL SPOT HEDGE ----------
    # Disabled by default. Expose it for later tuning only.
    ENABLE_UNDERLYING_HEDGE = False
    HEDGE_DELTA_THRESHOLD = 180.0
    HEDGE_SIZE = 20
    HEDGE_EDGE = 1.0

    def _book(self, od: OrderDepth):
        if not od.buy_orders or not od.sell_orders:
            return None
        buys = {int(p): abs(int(v)) for p, v in od.buy_orders.items()}
        sells = {int(p): abs(int(v)) for p, v in od.sell_orders.items()}
        bb = max(buys)
        ba = min(sells)
        return {
            "buys": dict(sorted(buys.items(), reverse=True)),
            "sells": dict(sorted(sells.items())),
            "bb": bb,
            "ba": ba,
            "bv": buys[bb],
            "av": sells[ba],
            "spread": ba - bb,
            "touch_mid": 0.5 * (bb + ba),
        }

    @staticmethod
    def _clip(value: float, lo: float, hi: float) -> float:
        return max(lo, min(hi, value))

    def _cap_size(
        self,
        max_size: int,
        pos: int,
        side: str,
        cap: int,
        limit: int,
        size_mult: float = 1.0,
    ) -> int:
        if cap <= 0:
            return 0
        ratio = 1.0 - min(0.7, abs(pos) / limit)
        if (side == "buy" and pos > 0) or (side == "sell" and pos < 0):
            ratio = max(0.3, ratio - 0.3)
        target = int(round(max_size * ratio * size_mult))
        return max(0, min(cap, target))

    @staticmethod
    def _opt_theo(S: float, K: int, T: float, sigma: float) -> float:
        if T <= 0 or sigma <= 0:
            return max(0.0, S - K)
        sq = sigma * math.sqrt(T)
        d1 = (math.log(S / K) + 0.5 * sigma * sigma * T) / sq
        d2 = d1 - sq
        return S * _N.cdf(d1) - K * _N.cdf(d2)

    @staticmethod
    def _opt_delta(S: float, K: int, T: float, sigma: float) -> float:
        if T <= 0 or sigma <= 0:
            return 1.0 if S > K else 0.0
        sq = sigma * math.sqrt(T)
        d1 = (math.log(S / K) + 0.5 * sigma * sigma * T) / sq
        return _N.cdf(d1)

    @staticmethod
    def _tte_years(ts: int) -> float:
        tte_days = TTE_DAYS_LIVE - ts / 1e6
        if tte_days <= 0:
            return 0.0
        return tte_days / DAYS_PER_YEAR

    def _flatten_visible(
        self,
        name: str,
        book: dict,
        working: int,
        chunk: int,
    ) -> Tuple[List[Order], int]:
        orders: List[Order] = []
        if working > 0:
            remaining = min(working, chunk)
            for bp, bv in book["buys"].items():
                q = min(bv, remaining)
                if q > 0:
                    orders.append(Order(name, bp, -q))
                    working -= q
                    remaining -= q
                if remaining <= 0:
                    break
        elif working < 0:
            remaining = min(-working, chunk)
            for ap, av in book["sells"].items():
                q = min(av, remaining)
                if q > 0:
                    orders.append(Order(name, ap, q))
                    working += q
                    remaining -= q
                if remaining <= 0:
                    break
        return orders, working

    def _trade_hydrogel(
        self,
        od: OrderDepth,
        pos: int,
        prev_mid: Optional[float],
        ts: int,
    ) -> Tuple[List[Order], float]:
        prod = "HYDROGEL_PACK"
        limit = self.LIMITS[prod]
        book = self._book(od)
        if not book:
            return [], prev_mid if prev_mid is not None else 0.0
        bb, ba = book["bb"], book["ba"]
        spread = book["spread"]
        touch_mid = book["touch_mid"]

        shock = prev_mid is not None and abs(touch_mid - prev_mid) > self.H_SHOCK_MOVE
        if shock:
            fair = touch_mid
        else:
            fair_adj = self._clip(touch_mid - self.H_ANCHOR, -self.H_CLIP, self.H_CLIP)
            fair = self.H_ANCHOR + fair_adj

        working = pos
        orders: List[Order] = []

        if ts >= self.H_ENDGAME_START and abs(working) >= self.H_ENDGAME_POS:
            flat_orders, working = self._flatten_visible(
                prod, book, working, self.H_ENDGAME_CHUNK
            )
            orders.extend(flat_orders)
            return orders, touch_mid

        for ap, av in book["sells"].items():
            cap = limit - working
            if cap <= 0:
                break
            skew = fair - self.H_INV_SKEW * working
            if ap <= skew - self.H_TAKE_EDGE:
                q = min(av, cap)
                if q > 0:
                    orders.append(Order(prod, ap, q))
                    working += q
            elif working < 0 and ap <= skew + self.H_REDUCE_EDGE:
                q = min(av, cap, abs(working))
                if q > 0:
                    orders.append(Order(prod, ap, q))
                    working += q

        for bp, bv in book["buys"].items():
            cap = limit + working
            if cap <= 0:
                break
            skew = fair - self.H_INV_SKEW * working
            if bp >= skew + self.H_TAKE_EDGE:
                q = min(bv, cap)
                if q > 0:
                    orders.append(Order(prod, bp, -q))
                    working -= q
            elif working > 0 and bp >= skew - self.H_REDUCE_EDGE:
                q = min(bv, cap, working)
                if q > 0:
                    orders.append(Order(prod, bp, -q))
                    working -= q

        if shock:
            return orders, touch_mid

        skew = fair - self.H_INV_SKEW * working
        buy_cap = max(0, limit - working)
        sell_cap = max(0, limit + working)
        bid_size = self._cap_size(self.H_MAX_POST_SIZE, working, "buy", buy_cap, limit)
        ask_size = self._cap_size(self.H_MAX_POST_SIZE, working, "sell", sell_cap, limit)

        if spread >= self.H_WIDE_SPREAD:
            bid_price = min(bb + 1, math.floor(skew - self.H_PENNY_EDGE))
            ask_price = max(ba - 1, math.ceil(skew + self.H_PENNY_EDGE))
        else:
            bid_price = math.floor(skew - self.H_PASSIVE_OFFSET)
            ask_price = math.ceil(skew + self.H_PASSIVE_OFFSET)
        bid_price = min(int(bid_price), ba - 1, math.floor(fair) - 1)
        ask_price = max(int(ask_price), bb + 1, math.ceil(fair) + 1)

        if bid_price < ask_price:
            if bid_size > 0:
                orders.append(Order(prod, bid_price, bid_size))
            if ask_size > 0:
                orders.append(Order(prod, ask_price, -ask_size))
        return orders, touch_mid

    def _voucher_context(
        self,
        name: str,
        spot_mid: float,
        books: Dict[str, dict],
    ) -> Tuple[float, float]:
        other_name = "VEV_4500" if name == "VEV_4000" else "VEV_4000"
        other_book = books.get(other_name)
        if other_book is None:
            return spot_mid, 0.0

        other_synth = other_book["touch_mid"] + self.VOUCHER_STRIKES[other_name]
        disagreement = other_synth - spot_mid
        blended_spot = spot_mid + self.V_SIBLING_BLEND * self._clip(
            disagreement, -self.V_SIBLING_BLEND_CAP, self.V_SIBLING_BLEND_CAP
        )
        return blended_spot, disagreement

    def _trade_deep_itm(
        self,
        name: str,
        K: int,
        od: OrderDepth,
        pos: int,
        spot_mid: float,
        books: Dict[str, dict],
        T: float,
        ts: int,
    ) -> List[Order]:
        limit = self.LIMITS[name]
        book = self._book(od)
        if not book:
            return []

        spot_for_fair, disagreement = self._voucher_context(name, spot_mid, books)
        confidence_bad = abs(disagreement) > self.V_CONFIRM_THRESHOLD
        extra_edge = self.V_CONFIRM_WIDEN if confidence_bad else 0.0
        size_mult = self.V_CONFIRM_SIZE_MULT if confidence_bad else 1.0

        bb, ba = book["bb"], book["ba"]
        spread = book["spread"]
        fair = self._opt_theo(spot_for_fair, K, T, self.V_SIGMA)
        working = pos
        orders: List[Order] = []

        if ts >= self.V_ENDGAME_START and abs(working) >= self.V_ENDGAME_POS:
            flat_orders, _ = self._flatten_visible(
                name, book, working, self.V_ENDGAME_CHUNK
            )
            return flat_orders

        for ap, av in book["sells"].items():
            cap = limit - working
            if cap <= 0:
                break
            skew = fair - self.V_INV_SKEW * working
            if ap <= skew - (self.V_TAKE_EDGE + extra_edge):
                q = min(av, cap)
                if q > 0:
                    orders.append(Order(name, ap, q))
                    working += q
            elif working < 0 and ap <= skew + self.V_REDUCE_EDGE:
                q = min(av, cap, abs(working))
                if q > 0:
                    orders.append(Order(name, ap, q))
                    working += q

        for bp, bv in book["buys"].items():
            cap = limit + working
            if cap <= 0:
                break
            skew = fair - self.V_INV_SKEW * working
            if bp >= skew + (self.V_TAKE_EDGE + extra_edge):
                q = min(bv, cap)
                if q > 0:
                    orders.append(Order(name, bp, -q))
                    working -= q
            elif working > 0 and bp >= skew - self.V_REDUCE_EDGE:
                q = min(bv, cap, working)
                if q > 0:
                    orders.append(Order(name, bp, -q))
                    working -= q

        skew = fair - self.V_INV_SKEW * working
        buy_cap = max(0, limit - working)
        sell_cap = max(0, limit + working)
        bid_size = self._cap_size(
            self.V_MAX_POST_SIZE, working, "buy", buy_cap, limit, size_mult
        )
        ask_size = self._cap_size(
            self.V_MAX_POST_SIZE, working, "sell", sell_cap, limit, size_mult
        )

        if spread >= self.V_WIDE_SPREAD:
            bid_price = min(bb + 1, math.floor(skew - self.V_PENNY_EDGE - extra_edge))
            ask_price = max(ba - 1, math.ceil(skew + self.V_PENNY_EDGE + extra_edge))
            bid_price = min(int(bid_price), ba - 1, math.floor(fair) - 1)
            ask_price = max(int(ask_price), bb + 1, math.ceil(fair) + 1)
            if bid_price < ask_price:
                if bid_size > 0:
                    orders.append(Order(name, bid_price, bid_size))
                if ask_size > 0:
                    orders.append(Order(name, ask_price, -ask_size))
        return orders

    def _maybe_hedge_underlying(
        self,
        state: TradingState,
        spot_book: dict,
        T: float,
    ) -> List[Order]:
        if not self.ENABLE_UNDERLYING_HEDGE:
            return []

        spot_pos = state.position.get("VELVETFRUIT_EXTRACT", 0)
        net_delta = float(spot_pos)
        spot_mid = spot_book["touch_mid"]

        for name, K in self.VOUCHER_STRIKES.items():
            p = state.position.get(name, 0)
            net_delta += p * self._opt_delta(spot_mid, K, T, self.V_SIGMA)

        if abs(net_delta) < self.HEDGE_DELTA_THRESHOLD:
            return []

        orders: List[Order] = []
        name = "VELVETFRUIT_EXTRACT"
        bb, ba = spot_book["bb"], spot_book["ba"]
        if net_delta > 0:
            q = min(self.HEDGE_SIZE, self.LIMITS[name] + spot_pos, spot_book["bv"])
            if q > 0 and bb >= spot_mid - self.HEDGE_EDGE:
                orders.append(Order(name, bb, -q))
        else:
            q = min(self.HEDGE_SIZE, self.LIMITS[name] - spot_pos, spot_book["av"])
            if q > 0 and ba <= spot_mid + self.HEDGE_EDGE:
                orders.append(Order(name, ba, q))
        return orders

    def run(self, state: TradingState):
        saved: Dict = {}
        if state.traderData:
            try:
                saved = json.loads(state.traderData)
            except Exception:
                saved = {}

        result: Dict[str, List[Order]] = {}
        pos = state.position

        if "HYDROGEL_PACK" in state.order_depths:
            prev_mid = saved.get("h_prev_mid")
            orders, new_mid = self._trade_hydrogel(
                state.order_depths["HYDROGEL_PACK"],
                pos.get("HYDROGEL_PACK", 0),
                prev_mid,
                state.timestamp,
            )
            result["HYDROGEL_PACK"] = orders
            saved["h_prev_mid"] = new_mid

        books: Dict[str, dict] = {}
        for name in ("VELVETFRUIT_EXTRACT", "VEV_4000", "VEV_4500"):
            od = state.order_depths.get(name)
            if od is not None:
                book = self._book(od)
                if book is not None:
                    books[name] = book

        spot_book = books.get("VELVETFRUIT_EXTRACT")
        if spot_book is not None:
            spot_mid = spot_book["touch_mid"]
            T = self._tte_years(state.timestamp)

            for name, K in self.VOUCHER_STRIKES.items():
                od = state.order_depths.get(name)
                if od is None:
                    continue
                result[name] = self._trade_deep_itm(
                    name,
                    K,
                    od,
                    pos.get(name, 0),
                    spot_mid,
                    books,
                    T,
                    state.timestamp,
                )

            hedge_orders = self._maybe_hedge_underlying(state, spot_book, T)
            if hedge_orders:
                result["VELVETFRUIT_EXTRACT"] = hedge_orders

        return result, 0, json.dumps(saved)


# Upload-safe wrapper overrides.

class ParentTrader(BaseTrader):
    TREND_FAST_ALPHA = 0.06
    TREND_SLOW_ALPHA = 0.01
    TREND_TRIGGER = 8.0
    TREND_FAIR_BETA = 0.20
    TREND_EDGE_WIDEN = 0.75
    TREND_SIZE_MULT = 0.50

    ENABLE_UNDERLYING_HEDGE = True
    HEDGE_DELTA_THRESHOLD = 150.0
    HEDGE_SIZE = 15
    HEDGE_EDGE = 0.5

    def _update_spot_trend(self, saved: Dict, spot_mid: float) -> float:
        fast = float(saved.get("spot_ema_fast", spot_mid))
        slow = float(saved.get("spot_ema_slow", spot_mid))
        fast = (1.0 - self.TREND_FAST_ALPHA) * fast + self.TREND_FAST_ALPHA * spot_mid
        slow = (1.0 - self.TREND_SLOW_ALPHA) * slow + self.TREND_SLOW_ALPHA * spot_mid
        saved["spot_ema_fast"] = fast
        saved["spot_ema_slow"] = slow
        return fast - slow

    def _trade_deep_itm(
        self,
        name: str,
        K: int,
        od,
        pos: int,
        spot_mid: float,
        books: Dict[str, dict],
        T: float,
        ts: int,
    ) -> List[Order]:
        limit = self.LIMITS[name]
        book = self._book(od)
        if not book:
            return []

        spot_for_fair, disagreement = self._voucher_context(name, spot_mid, books)
        trend = getattr(self, "_ctx_spot_trend", 0.0)

        bb, ba = book["bb"], book["ba"]
        spread = book["spread"]
        working = pos
        fair = self._opt_theo(spot_for_fair, K, T, self.V_SIGMA)

        adverse_long = trend <= -self.TREND_TRIGGER and working >= 0
        adverse_short = trend >= self.TREND_TRIGGER and working <= 0

        confidence_bad = abs(disagreement) > self.V_CONFIRM_THRESHOLD
        extra_edge = self.V_CONFIRM_WIDEN if confidence_bad else 0.0
        size_mult = self.V_CONFIRM_SIZE_MULT if confidence_bad else 1.0

        if adverse_long or adverse_short:
            fair += self.TREND_FAIR_BETA * trend
            extra_edge += self.TREND_EDGE_WIDEN
            size_mult *= self.TREND_SIZE_MULT

        orders: List[Order] = []

        if ts >= self.V_ENDGAME_START and abs(working) >= self.V_ENDGAME_POS:
            flat_orders, _ = self._flatten_visible(
                name, book, working, self.V_ENDGAME_CHUNK
            )
            return flat_orders

        for ap, av in book["sells"].items():
            cap = limit - working
            if cap <= 0:
                break
            skew = fair - self.V_INV_SKEW * working
            if ap <= skew - (self.V_TAKE_EDGE + extra_edge):
                q = min(av, cap)
                if q > 0:
                    orders.append(Order(name, ap, q))
                    working += q
            elif working < 0 and ap <= skew + self.V_REDUCE_EDGE:
                q = min(av, cap, abs(working))
                if q > 0:
                    orders.append(Order(name, ap, q))
                    working += q

        for bp, bv in book["buys"].items():
            cap = limit + working
            if cap <= 0:
                break
            skew = fair - self.V_INV_SKEW * working
            if bp >= skew + (self.V_TAKE_EDGE + extra_edge):
                q = min(bv, cap)
                if q > 0:
                    orders.append(Order(name, bp, -q))
                    working -= q
            elif working > 0 and bp >= skew - self.V_REDUCE_EDGE:
                q = min(bv, cap, working)
                if q > 0:
                    orders.append(Order(name, bp, -q))
                    working -= q

        skew = fair - self.V_INV_SKEW * working
        buy_cap = max(0, limit - working)
        sell_cap = max(0, limit + working)
        bid_size = self._cap_size(
            self.V_MAX_POST_SIZE, working, "buy", buy_cap, limit, size_mult
        )
        ask_size = self._cap_size(
            self.V_MAX_POST_SIZE, working, "sell", sell_cap, limit, size_mult
        )

        if spread >= self.V_WIDE_SPREAD:
            bid_price = min(bb + 1, math.floor(skew - self.V_PENNY_EDGE - extra_edge))
            ask_price = max(ba - 1, math.ceil(skew + self.V_PENNY_EDGE + extra_edge))
            bid_price = min(int(bid_price), ba - 1, math.floor(fair) - 1)
            ask_price = max(int(ask_price), bb + 1, math.ceil(fair) + 1)
            if bid_price < ask_price:
                if bid_size > 0:
                    orders.append(Order(name, bid_price, bid_size))
                if ask_size > 0:
                    orders.append(Order(name, ask_price, -ask_size))
        return orders

    def _maybe_hedge_underlying(self, state, spot_book: dict, T: float) -> List[Order]:
        trend = getattr(self, "_ctx_spot_trend", 0.0)
        if abs(trend) < self.TREND_TRIGGER:
            return []

        spot_pos = state.position.get("VELVETFRUIT_EXTRACT", 0)
        net_delta = float(spot_pos)
        spot_mid = spot_book["touch_mid"]

        for name, K in self.VOUCHER_STRIKES.items():
            p = state.position.get(name, 0)
            net_delta += p * self._opt_delta(spot_mid, K, T, self.V_SIGMA)

        orders: List[Order] = []
        name = "VELVETFRUIT_EXTRACT"
        bb, ba = spot_book["bb"], spot_book["ba"]

        if trend < 0 and net_delta > self.HEDGE_DELTA_THRESHOLD:
            q = min(self.HEDGE_SIZE, self.LIMITS[name] + spot_pos, spot_book["bv"])
            if q > 0 and bb >= spot_mid - self.HEDGE_EDGE:
                orders.append(Order(name, bb, -q))
        elif trend > 0 and net_delta < -self.HEDGE_DELTA_THRESHOLD:
            q = min(self.HEDGE_SIZE, self.LIMITS[name] - spot_pos, spot_book["av"])
            if q > 0 and ba <= spot_mid + self.HEDGE_EDGE:
                orders.append(Order(name, ba, q))
        return orders

    def run(self, state):
        saved: Dict = {}
        if state.traderData:
            try:
                saved = json.loads(state.traderData)
            except Exception:
                saved = {}

        result: Dict[str, List[Order]] = {}
        pos = state.position

        if "HYDROGEL_PACK" in state.order_depths:
            prev_mid = saved.get("h_prev_mid")
            orders, new_mid = self._trade_hydrogel(
                state.order_depths["HYDROGEL_PACK"],
                pos.get("HYDROGEL_PACK", 0),
                prev_mid,
                state.timestamp,
            )
            result["HYDROGEL_PACK"] = orders
            saved["h_prev_mid"] = new_mid

        books: Dict[str, dict] = {}
        for name in ("VELVETFRUIT_EXTRACT", "VEV_4000", "VEV_4500"):
            od = state.order_depths.get(name)
            if od is not None:
                book = self._book(od)
                if book is not None:
                    books[name] = book

        spot_book = books.get("VELVETFRUIT_EXTRACT")
        if spot_book is not None:
            spot_mid = spot_book["touch_mid"]
            self._ctx_spot_trend = self._update_spot_trend(saved, spot_mid)
            T = self._tte_years(state.timestamp)

            for name, K in self.VOUCHER_STRIKES.items():
                od = state.order_depths.get(name)
                if od is None:
                    continue
                result[name] = self._trade_deep_itm(
                    name,
                    K,
                    od,
                    pos.get(name, 0),
                    spot_mid,
                    books,
                    T,
                    state.timestamp,
                )

            hedge_orders = self._maybe_hedge_underlying(state, spot_book, T)
            if hedge_orders:
                result["VELVETFRUIT_EXTRACT"] = hedge_orders

        return result, 0, json.dumps(saved)


# Upload-safe wrapper overrides.

class Trader(ParentTrader):
    C_SPOT_WEIGHT = 1.0
    C_SYNTH_WEIGHT = 8.0
    C_BLEND = 0.20
    C_BLEND_CAP = 5.0

    V_CONFIRM_THRESHOLD = 1.5
    V_CONFIRM_WIDEN = 0.75
    V_CONFIRM_SIZE_MULT = 0.45

    def _voucher_context(self, name: str, spot_mid: float, books):
        weighted_sum = self.C_SPOT_WEIGHT * spot_mid
        total_w = self.C_SPOT_WEIGHT
        for other_name, strike in self.VOUCHER_STRIKES.items():
            book = books.get(other_name)
            if book is None:
                continue
            synth = book["touch_mid"] + strike
            weight = self.C_SYNTH_WEIGHT / max(1.0, float(book["spread"]))
            weighted_sum += weight * synth
            total_w += weight

        consensus = weighted_sum / total_w if total_w > 0 else spot_mid
        disagreement = consensus - spot_mid
        blended_spot = spot_mid + self.C_BLEND * self._clip(
            disagreement, -self.C_BLEND_CAP, self.C_BLEND_CAP
        )
        return blended_spot, disagreement
