from __future__ import annotations

import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ROUND3_DIR = REPO_ROOT / "traders" / "round3"

AUTO_HEADER = (
    "# Auto-generated by `tools/build_round3_uploadsafe_variants.py`.\n"
    "# This file is intended for single-file IMC uploads.\n\n"
)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def rename_last_trader_class(text: str, new_name: str) -> str:
    patterns = [
        r"class Trader\(([^)]*)\):",
        r"class Trader:",
    ]
    candidates: list[tuple[int, int, str]] = []
    for pattern in patterns:
        for match in re.finditer(pattern, text):
            candidates.append((match.start(), match.end(), pattern))
    if not candidates:
        raise ValueError("Could not find `class Trader` in source text.")
    start, end, pattern = max(candidates, key=lambda item: item[0])
    original = text[start:end]
    if pattern == r"class Trader\(([^)]*)\):":
        base_name = re.match(pattern, original).group(1)  # type: ignore[union-attr]
        replacement = f"class {new_name}({base_name}):"
    else:
        replacement = f"class {new_name}:"
    return text[:start] + replacement + text[end:]


def extract_class_block(path: Path, parent_name: str) -> str:
    text = read_text(path)
    class_start = text.find("class Trader(")
    if class_start < 0:
        class_start = text.find("class Trader:")
    if class_start < 0:
        raise ValueError(f"Could not find Trader class block in {path}")
    class_block = text[class_start:].strip()
    class_block = re.sub(
        r"class Trader\(([^)]*)\):",
        f"class Trader({parent_name}):",
        class_block,
        count=1,
    )
    class_block = re.sub(
        r"class Trader:",
        f"class Trader({parent_name}):",
        class_block,
        count=1,
    )
    return class_block


def compose_variant_text(base_text: str, wrapper_path: Path, embedded_parent_name: str, wrapper_parent_name: str) -> str:
    embedded = rename_last_trader_class(base_text, embedded_parent_name).rstrip()
    class_block = extract_class_block(wrapper_path, wrapper_parent_name)
    return (
        embedded
        + "\n\n\n"
        + "# Upload-safe wrapper overrides.\n\n"
        + class_block
        + "\n"
    )


def write_variant(path: Path, source_name: str, base_name: str, text: str) -> None:
    payload = (
        AUTO_HEADER
        + f"# Variant source: `{source_name}`\n"
        + f"# Embedded base: `{base_name}`\n\n"
        + text
    )
    path.write_text(payload, encoding="utf-8")


def main() -> None:
    fundamental_base = read_text(ROUND3_DIR / "fundamental_v1.py")

    simple_specs = [
        (
            "fundamental_spot_anchor_uploadsafe_v1.py",
            "fundamental_spot_anchor_v1.py",
        ),
        (
            "fundamental_spot_anchor_hydro_vfe_regime_uploadsafe_v1.py",
            "fundamental_spot_anchor_hydro_vfe_regime_v1.py",
        ),
        (
            "fundamental_consensus_hedged_uploadsafe_v1.py",
            "fundamental_consensus_hedged_v1.py",
        ),
        (
            "fundamental_basis_coupled_uploadsafe_v1.py",
            "fundamental_basis_coupled_v1.py",
        ),
        (
            "fundamental_surface_level_uploadsafe_v1.py",
            "fundamental_surface_level_v1.py",
        ),
        (
            "fundamental_surface_gate_uploadsafe_v1.py",
            "fundamental_surface_gate_v1.py",
        ),
        (
            "fundamental_surface_slope_guard_uploadsafe_v1.py",
            "fundamental_surface_slope_guard_v1.py",
        ),
    ]

    for output_name, wrapper_name in simple_specs:
        text = compose_variant_text(
            fundamental_base,
            ROUND3_DIR / wrapper_name,
            embedded_parent_name="BaseTrader",
            wrapper_parent_name="BaseTrader",
        )
        write_variant(
            ROUND3_DIR / output_name,
            source_name=wrapper_name,
            base_name="fundamental_v1.py",
            text=text,
        )

    drift_guard_text = compose_variant_text(
        fundamental_base,
        ROUND3_DIR / "fundamental_drift_guard_v1.py",
        embedded_parent_name="BaseTrader",
        wrapper_parent_name="BaseTrader",
    )
    write_variant(
        ROUND3_DIR / "fundamental_drift_guard_uploadsafe_v1.py",
        source_name="fundamental_drift_guard_v1.py",
        base_name="fundamental_v1.py",
        text=drift_guard_text,
    )

    drift_basis_text = compose_variant_text(
        drift_guard_text,
        ROUND3_DIR / "fundamental_drift_basis_hedged_v1.py",
        embedded_parent_name="ParentTrader",
        wrapper_parent_name="ParentTrader",
    )
    write_variant(
        ROUND3_DIR / "fundamental_drift_basis_hedged_uploadsafe_v1.py",
        source_name="fundamental_drift_basis_hedged_v1.py",
        base_name="fundamental_drift_guard_uploadsafe_v1.py",
        text=drift_basis_text,
    )

    print("Generated upload-safe round-3 variants:")
    for path in sorted(ROUND3_DIR.glob("*_uploadsafe_v1.py")):
        print(path.relative_to(REPO_ROOT))


if __name__ == "__main__":
    main()
